export const portals = [
  { id: "lion", name: "Sigorta Lion", url: "https://lion.sigorta.online/trafik", adapter: "ihsan", group: "İhsan altyapısı", verifiedForm: true },
  { id: "bitikla", name: "Bi Tıkla Sigorta", url: "https://bitikla.sigorta.online/trafik", adapter: "ihsan", group: "İhsan altyapısı", verifiedForm: true },
  { id: "sigortabaz", name: "SigortaBaz", url: "https://teklif.sigortabaz.com/trafik", adapter: "ihsan", group: "İhsan altyapısı", verifiedForm: true },
  { id: "sigortamobil", name: "SigortaMobil", url: "https://sigortamobil.sigorta.online/trafik", adapter: "ihsan", group: "İhsan altyapısı", verifiedForm: true },
  { id: "tasalti", name: "Taşaltı Teklif", url: "https://tasalti.sigorta.online/trafik", adapter: "ihsan", group: "İhsan altyapısı", verifiedForm: true },
  { id: "sert", name: "Sert Sigorta", url: "https://sert.sigorta.online/trafik", adapter: "ihsan", group: "İhsan altyapısı", verifiedForm: false },
  { id: "nepratik", name: "Ne Pratik Sigorta", url: "https://nepratiksigorta.com/Trafik", adapter: "ihsan", group: "İhsan altyapısı", verifiedForm: false },
  { id: "iskenderun", name: "İskenderun Teklif", url: "https://iskenderun.sigorta.online/trafik", adapter: "ihsan", group: "İhsan altyapısı", verifiedForm: false },
  { id: "sigortammilli", name: "Sigortam Milli", url: "https://sigortammilli.com.tr/trafik-sigortasi/", adapter: "ihsan-frame", group: "İhsan altyapısı", verifiedForm: true },
  { id: "sigortam", name: "Sigortam.net", url: "https://www.sigortam.net/trafik-sigortasi", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true },
  { id: "sigortaladim", name: "Sigortaladım", url: "https://www.sigortaladim.com/zorunlu-trafik-sigortasi", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true },
  { id: "koalay", name: "Koalay", url: "https://www.koalay.com/zorunlu-trafik-sigortasi", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true },
  { id: "enuygun", name: "Enuygun Sigorta", url: "https://www.enuygunsigorta.com/zorunlu-trafik-sigortasi/", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true },
  { id: "sigortambir", name: "Sigortambir", url: "https://www.sigortambir.com/zorunlu-trafik-sigortasi", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true },
  { id: "sigorta7", name: "Sigorta7", url: "https://www.sigorta7.com/trafik-sigortasi", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true },
  { id: "sigortayeri", name: "Sigorta Yeri", url: "https://www.sigortayeri.com/arac-sigortasi/trafik-sigortasi", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true },
  { id: "sigortala", name: "Sigorta.la", url: "https://sigorta.la/page/trafik-sigortasi", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true },
  { id: "dijipol", name: "Dijipol", url: "https://www.dijipol.com/", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true },
  { id: "hangikredi", name: "HangiKredi Sigorta", url: "https://www.hangikredi.com/sigorta/zorunlu-trafik-sigortasi", adapter: "generic", group: "Banka / platform", verifiedForm: true },
  { id: "enpara", name: "Enpara Sigorta", url: "https://www.enpara.com/sigortalar/trafik-sigortasi", adapter: "generic", group: "Banka / platform", verifiedForm: true },
  { id: "hepiyi", name: "Hepiyi", url: "https://hepiyi.com.tr/trafik-sigortasi/form/arac-bilgileri", adapter: "generic", group: "Sigorta şirketi", verifiedForm: true },
  { id: "quick", name: "Quick Sigorta", url: "https://www.quicksigorta.com/zorunlu-trafik-sigortasi", adapter: "generic", group: "Sigorta şirketi", verifiedForm: true },
  { id: "sompo", name: "Sompo Sigorta", url: "https://www.somposigorta.com.tr/trafik-sigortasi", adapter: "generic", group: "Sigorta şirketi", verifiedForm: true },
  { id: "ethica", name: "Ethica Sigorta", url: "https://www.ethicasigorta.com.tr/trafik-sigortasi", adapter: "generic", group: "Sigorta şirketi", verifiedForm: true },
  { id: "policekes", name: "PoliçeKes", url: "https://www.policekes.com/", adapter: "generic", group: "Karşılaştırma sitesi", verifiedForm: true }
];

export const insurerAliases = [
  ["AKSİGORTA", ["AKSİGORTA", "AK SIGORTA"]],
  ["ALLIANZ", ["ALLIANZ"]],
  ["ANADOLU SİGORTA", ["ANADOLU SİGORTA", "ANADOLU SIGORTA"]],
  ["ANKARA SİGORTA", ["ANKARA SİGORTA", "ANKARA SIGORTA"]],
  ["ATLAS MUTUEL", ["ATLAS MUTUEL", "ATLAS"]],
  ["AXA SİGORTA", ["AXA SİGORTA", "AXA SIGORTA", "AXA"]],
  ["BEREKET SİGORTA", ["BEREKET"]],
  ["CORPUS SİGORTA", ["CORPUS"]],
  ["DOĞA SİGORTA", ["DOĞA SİGORTA", "DOGA SIGORTA", "DOĞA"]],
  ["ETHICA SİGORTA", ["ETHICA"]],
  ["EUREKO SİGORTA", ["EUREKO"]],
  ["GENERALI", ["GENERALI"]],
  ["HDI SİGORTA", ["HDI SİGORTA", "HDI SIGORTA", "HDI"]],
  ["HEPİYİ SİGORTA", ["HEPİYİ", "HEPIYI"]],
  ["KORU SİGORTA", ["KORU SİGORTA", "KORU SIGORTA"]],
  ["MAGDEBURGER", ["MAGDEBURGER"]],
  ["MAPFRE SİGORTA", ["MAPFRE SİGORTA", "MAPFRE SIGORTA", "MAPFRE"]],
  ["NEOVA SİGORTA", ["NEOVA"]],
  ["ORİENT SİGORTA", ["ORIENT", "ORİENT"]],
  ["QUICK SİGORTA", ["QUICK"]],
  ["RAY SİGORTA", ["RAY SİGORTA", "RAY SIGORTA"]],
  ["SOMPO SİGORTA", ["SOMPO"]],
  ["TÜRK NİPPON", ["TÜRK NİPPON", "TURK NIPPON"]],
  ["TÜRKİYE SİGORTA", ["TÜRKİYE SİGORTA", "TURKIYE SIGORTA"]],
  ["UNICO SİGORTA", ["UNICO"]],
  ["ZURICH SİGORTA", ["ZURICH"]]
];
